# DO NOT EDIT THIS FILE
#
# Boot script for Sophgo SG2000/SG2002 (Milkv Duo S, etc.)
# This script sets up memory addresses and uses sysboot to parse extlinux.conf
#
# The vendor U-Boot 2021.10 doesn't define standard distro boot variables,
# so we must set them here before invoking sysboot.
#

# Memory layout for SG2000 (512MB RAM at 0x80000000)
# kernel_addr_r: Kernel load address
# fdt_addr_r: Device tree load address (must not overlap with decompressed kernel!)
#             RISC-V kernel decompresses to ~20MB, ARM64 is ~17MB uncompressed
#             Using 0x82000000 (30MB offset) to be safe for both architectures
# ramdisk_addr_r: Initrd load address
setenv kernel_addr_r 0x80200000
setenv fdt_addr_r 0x82000000
setenv ramdisk_addr_r 0x86000000

# Boot partition is FAT on mmc 0:1
# Use sysboot to parse extlinux/extlinux.conf which contains:
# - kernel path
# - initrd path
# - device tree path
# - root filesystem UUID and boot arguments
echo "Booting from extlinux.conf..."
sysboot mmc 0:1 fat ${kernel_addr_r} /extlinux/extlinux.conf

# Fallback message if sysboot fails
echo "Boot failed! Check extlinux/extlinux.conf"
